version: '3.8'

services:
  # Demo Gateway - No auth required on port 8000
  gateway-dev:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./auth:/app/auth
      - ./common:/app/common
      - ./.env.dev:/app/.env.dev
    environment:
      - ENV=dev
    command: ["uvicorn", "main_dev:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - budget-service
      - savings-service
      - insights-service

  # Production Gateway - Auth required on port 8080
  gateway-prod:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./auth:/app/auth
      - ./common:/app/common
      - ./.env.prod:/app/.env.prod
    environment:
      - ENV=prod
      - SECRET_KEY=${SECRET_KEY:-production-secret-key-please-change-this}
    command: ["uvicorn", "main_prod:app", "--host", "0.0.0.0", "--port", "8080"]
    depends_on:
      - budget-service
      - savings-service
      - insights-service

  budget-service:
    build: ./services/budget-service
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  savings-service:
    build: ./services/savings-service
    ports:
      - "8002:8000"
    environment:
      - ENVIRONMENT=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  insights-service:
    build: ./services/insights-service
    ports:
      - "8003:8000"
    environment:
      - ENVIRONMENT=development
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8004:8000"
    environment:
      - BUDGET_SERVICE_URL=http://budget-service:8000
      - SAVINGS_SERVICE_URL=http://savings-service:8000
      - INSIGHTS_SERVICE_URL=http://insights-service:8000
    depends_on:
      - budget-service
      - savings-service
      - insights-service

volumes:
  redis-data:
